### ISSUE TITLE
[ISSUE] Memory Optimization Utilizing ZipList  is Required 

### ISSUE THREAD

**Issue by wonkiChoi** [addb-swstarlab/addb#1]
A default data structure, Hash type, is not appropriate in case that the structure has small amounts of entries.

We need to optimize the data structure to reduce the memory usage of Redis.

Using Ziplist under a predefined threshold can be a possible solution.

**Comment by hshs1103** [comment]
We fixed th bug by modifying the ziplist generation method. 

The result of simple unit test is show below.

![image](https://user-images.githubusercontent.com/20452176/61192541-fdfb2500-a6ef-11e9-9532-b358bd6f8b57.png)

After setting the ziplist entry maximum variable (hash-max-ziplist-entries) to 10, we inserted 20 key-value pairs in Redis. At this time, rowgroup_size and columnvector_size are set to 1. 

After 10 key-value pairs are inserted, ziplist is converted to hash normally, and the result of scan is normally output as below.

![image](https://user-images.githubusercontent.com/20452176/61192566-3b5fb280-a6f0-11e9-9b09-281138ff1234.png)
