### ISSUE TITLE
Avoid vector iteration in Scan operation

### ISSUE THREAD

**Issue by wonkiChoi** [addb-swstarlab/addb#5]
In fpScan, transferring the batches of column values will improve the scan performance.

In the current version, data is transferred to SparkSQL in form of row format.

Lots of iterations generate unnecessary computing overhead. 

SparkRedisConnector is also required to support this modification

**Comment by arbc139** [comment]
I implemented iterator-based scanning method on Redis-RocksDB.
SparkRedisConnector is still required to support.
