### ISSUE TITLE
[fpWriteCommand]Suggest processing of empty string is possible

### ISSUE THREAD

**Issue by Lihaolin-dataE** [addb-swstarlab/addb#7]
Hello. I am majoring in computer science at YUST and am interested in ADDB. 

During code review of how data is stored, there are parts that need to be supplemented and left behind.

The addb_table.c file in the v1.1.0 branch shows only processing for null value.

Considering the frequency of the empty string in addition to the null value, we suggest adding processing parts for empty string.

**Comment by addb-swstarlab** [comment]
@Lihaolin-dataE 

Thanks for the comments. After discussing with the development team, we think it is good to add handling for empty strings.

We will reflect on the case asap.
